// js/prestige_upgrades.js

// Ensure formatNumber and formatTime are accessible if used in description functions.
// They are defined in main.js; if prestigeUpgrades.js is loaded first,
// we might need to pass them or ensure they are on window scope from main.js.
// For simplicity, descriptionFunction will now just get the next level's potential effect.
// The main.js render function will combine current and next.

window.prestigeUpgradesList = [
    {
        id: 'startingGoldBoost',
        name: 'Initial Investment Fund',
        description: "Grants additional starting Gold after each Ascension. Helps kickstart your new realm.",
        maxLevel: 50,
        costFormula: (level) => Math.floor(1 * Math.pow(1.5, level)) + 1, // Cost: 2, 2, 3, 4, 5, 7, 10 RS...
        effectPerLevel: 500, // Each level gives +500 Gold
        currentEffectDisplay: (currentLevel) => `+${formatNumber(BASE_STARTING_GOLD + (currentLevel * 500), true)} Total Starting Gold`,
        nextLevelEffectDisplay: (nextLevel) => `+${formatNumber(BASE_STARTING_GOLD + (nextLevel * 500), true)} Total Starting Gold`,
        type: 'starting_gold'
    },
    {
        id: 'cosmicBlessing',
        name: 'Cosmic Blessing',
        description: "Permanently increases all income generated by your properties.",
        maxLevel: 100, // Max +500%
        costFormula: (level) => Math.floor(3 * Math.pow(1.45, level)) + 2, // Cost: 5, 7, 10, 14, 19 RS...
        effectPerLevel: 0.05, // Each level gives +5% income (0.05)
        currentEffectDisplay: (currentLevel) => `+${(currentLevel * 5).toFixed(1)}% All Income`,
        nextLevelEffectDisplay: (nextLevel) => `+${(nextLevel * 5).toFixed(1)}% All Income`,
        type: 'income_multiplier_all'
    },
    {
        id: 'efficientRealms',
        name: 'Realm Efficiency',
        description: "Permanently reduces the purchase and upgrade costs of all properties.",
        maxLevel: 40, // Max 20% reduction
        costFormula: (level) => Math.floor(5 * Math.pow(1.55, level)) + 3, // Cost: 8, 11, 15, 22, 32 RS...
        effectPerLevel: 0.005, // Each level reduces cost by 0.5% (0.005)
        currentEffectDisplay: (currentLevel) => `-${(currentLevel * 0.5).toFixed(1)}% All Costs`,
        nextLevelEffectDisplay: (nextLevel) => `-${(nextLevel * 0.5).toFixed(1)}% All Costs`,
        type: 'cost_reduction_all'
    },
    {
        id: 'shardHoarder',
        name: 'Shard Scavenger',
        description: "Increases the amount of Realm Shards gained from each Ascension.",
        maxLevel: 50, // Max +100%
        costFormula: (level) => Math.floor(15 * Math.pow(1.8, level)), // Cost: 15, 27, 48, 87 RS... (Expensive)
        effectPerLevel: 0.02, // Each level gives +2% more shards
        currentEffectDisplay: (currentLevel) => `+${currentLevel * 2}% Realm Shards Gained`,
        nextLevelEffectDisplay: (nextLevel) => `+${nextLevel * 2}% Realm Shards Gained`,
        type: 'shard_gain_multiplier'
    },
    {
        id: 'offlineTimeCapBoost',
        name: 'Temporal Anchor',
        description: "Increases the maximum duration for which offline earnings are calculated.",
        maxLevel: 20, // Max +10 hours to the base (e.g. 2 hours base + 10 hours = 12 hours total)
        costFormula: (level) => Math.floor(4 * Math.pow(1.6, level)) + 2, // Cost: 6, 8, 11, 16 RS...
        effectPerLevel: 30 * 60, // Each level adds 30 minutes in seconds
        currentEffectDisplay: (currentLevel) => `+${formatTime(currentLevel * 30 * 60)} Max Offline Time`,
        nextLevelEffectDisplay: (nextLevel) => `+${formatTime(nextLevel * 30 * 60)} Max Offline Time`,
        type: 'offline_cap_increase_seconds'
    },
    {
        id: 'offlineMultiplierBoost',
        name: 'Lingering Echoes',
        description: "Boosts the effectiveness (multiplier) of your offline earnings.",
        maxLevel: 20, // Max +100% effectiveness
        costFormula: (level) => Math.floor(6 * Math.pow(1.65, level)) + 2, // Cost: 8, 11, 17, 26 RS...
        effectPerLevel: 0.05, // Each level adds +5% effectiveness
        currentEffectDisplay: (currentLevel) => `+${currentLevel * 5}% Offline Earnings Multiplier`,
        nextLevelEffectDisplay: (nextLevel) => `+${nextLevel * 5}% Offline Earnings Multiplier`,
        type: 'offline_multiplier_increase'
    },
    {
        id: 'unlockCelestialForge',
        name: 'Unlock: Celestial Forge',
        description: "Unlocks a new, powerful Tier 6 'Ascended' property in the main game: The Celestial Forge. (Property itself must still be purchased with Gold).",
        maxLevel: 1, // One-time unlock
        costFormula: (level) => (level === 0 ? 100 : Infinity), // Cost 100 RS, then unpurchasable
        effectPerLevel: 1, // Effect is just a flag (level 1 means unlocked)
        currentEffectDisplay: (currentLevel) => (currentLevel > 0 ? "Celestial Forge Unlocked!" : "Locked"),
        nextLevelEffectDisplay: (nextLevel) => (nextLevel > 0 ? "Celestial Forge Unlocked!" : "Unlock Celestial Forge"),
        type: 'unlock_feature' // Or 'unlock_ascended_property'
    }
];
